project:
  type: website
  output-dir: docs

website:
  title: "Megan Zhao"
  # adding tab icon
  favicon: media/monkey-drawing-bw.png
  navbar:
    title: false
    # adding navbar icon
    logo: media/monkey-drawing.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - posts.qmd
      - href: cv.qmd
        text: Resume
      - href: misc.qmd
        text: Photos
  page-footer: 
    right: Copyright 2026, Megan Zhao

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
      dark: 
        - darkly
        - styles.scss
    mainfont: Elms Sans
    css: styles.scss
    toc: true
    page-layout: full



