{
  "hash": "afb1a92282163012fe05ffc29e322c3d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ENVS 193DS Homework Assignment #03\"\ndescription: \"This is a homework assignment from my ENVS 193DS class, intended to help develop experience working with dataframes. It includes practicing correlation visualization, correlation calculations, visualizing personal data, developing an affective visualization, and statistical critiques. Please note discrepencies within code of text formatting using single instead of double quotes.\"\ndate: 5/28/26\ncategories: [Coding, R]\nimage: hw03-thumbnail.png\ndraft: false\n---\nYou can also explore the code here: [ENVS 193DS - HW 03 {{< fa file-pdf title= \"pdf\" >}}](ENVS-193DS_homework-03-DOC.pdf)</p>\n\n---\ntitle: \"ENVS 193DS Homework Assignment 03\"\nauthor: \"Megan Zhao\"\ndate: 5/28/26\nmessages: false\nwarning: false\n---\n# Set Up\n\nPackages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# reading in packages\nlibrary(tidyverse)\nlibrary(here)\nlibrary(janitor)\nlibrary(readxl)\n```\n:::\n\n\nData: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating object from 'kelp' from data\nkelp <- read.csv('temp-kelp.csv')\n\n# creating object 'mz_data' from data\nmz_data <- read_xlsx('193DS-personal-data.xlsx')\n```\n:::\n\n\nCleaning\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new object called 'mz_clean' from 'mz_data'\nmz_clean <- mz_data |> \n  # clean names\n  clean_names() |>\n  # create new data column 'completed_v_intended'\n  mutate(\n    # use data from select columns to calculate new column\n    completed_v_intended = (\n      number_of_completed_tasks/number_of_intended_tasks\n    ) * 100)\n```\n:::\n\n\nAesthetics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# setting figure themes\ntheme_set(theme_classic())\n```\n:::\n\n\n# Problem 1\n\n## a.\n\nThe appropriate tests to determine the strength of the relationship between temperature and giant kelp frond elongation rate are the Pearson's correlation test and the Spearman rank correlation test. While both tests can be used to determine relationship strength, Pearson's correlation is parametric, assuming continuous and normally distributed variables with independent observations, and explores the linear relationship between variables. On the other hand, the Spearman rank correlation is non-parametric, assuming independent observations, and explores the monotonic relationship between variables.\n\n## b.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(\n  # starting data frame\n  data = kelp,\n  # x-axis\n  mapping = aes(x = temp_c,\n                # y-axis\n                y = kelp_elong)\n) +\n  # first layer: points\n  geom_point(\n    # coloring points\n    color = 'chartreuse4',\n    # changing opacity\n    alpha = 0.8\n  ) +\n  # relabelling x-axis, y-axis, and title\n  labs(\n    # label x-axis\n    x = 'Ocean Temperature (°C)',\n    # label y-axis\n    y = expression(paste('Giant Kelp Frond Elongation Rate (cm day' ^-1,')')),\n    # add chart title\n    title = 'Ocean Temperature and Giant Kelp Frond Growth Correlation')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/test-1-visualization-1.png){width=672}\n:::\n:::\n\n\n## c.\n\n### assumption checking \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(\n  # starting data frame\n  data = kelp,\n  # x-axis\n  mapping = aes(x = temp_c,\n                # y-axis\n                y = kelp_elong)\n) +\n  # first layer: points\n  geom_point(\n    # coloring points\n    color = 'chartreuse4',\n    # changing opacity\n    alpha = 0.8\n  ) +\n  # relabelling x-axis, y-axis, and title\n  labs(\n    # label x-axis\n    x = 'Ocean Temperature (°C)',\n    # label y-axis\n    y = expression(paste('Giant Kelp Frond Elongation Rate (cm day' ^-1,')')),\n    # add chart title\n    title = 'Ocean Temperature and Giant Kelp Frond Growth Correlation')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/assumption-checking-1-1.png){width=672}\n:::\n:::\n\n\nBecause I plan on running a Spearmans rank correlation test, I only had to check if my data was independent and monotonic. I checked independence by ensuring that proper methodology was being used when collecting data (data collected individually, stated in Problem 1 introduction), and for a monotonic relationship by creating a visualization. After checking my assumptions, I concluded that I have independent observations, and that my data is monotonic -- as ocean temperature increases, giant kelp frond elongation rate decreases.\n\n### test running\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# correlation test\ncor.test(\n  # y-variable\n  kelp$kelp_elong,\n  # x-variable\n  kelp$temp_c,\n  # use spearmans test\n  method = 'spearman',\n  # use normal p-approximation\n  exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  kelp$kelp_elong and kelp$temp_c\nS = 9216.1, p-value = 1.29e-05\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.6891684 \n```\n\n\n:::\n:::\n\n\n## d.\n\nTo evaluate the strength of the relationship between temperature and giant kelp frond elongation rate I used a Spearmans rank correlation test. I chose to use Spearmans test over Pearsons as I did not check for normality nor a linear relationship. After running the Spearmans test, I found a moderate negative relationship between ocean temperature and giant kelp frond elongation rate (Spearman $\\rho$ = -0.69, S = 9216.1, p = 1.29 * 10^-5^, $\\alpha$ = 0.05).\n\n## e.\n\nThere is a moderate correlation between ocean temperature and giant kelp frond elongation rate. As temperature increases, kelp frond elongation rate decreases, indicating decreased growth with warming temperatures. This information is important for giant kelp health -- the ongoing climate crisis and subsequent consistently warming ocean temperatures hold significant negative implications for giant kelp health over time; without action against climate change (and warming oceans), giant kelp populations will degrade over time, potentially leading to larger-scale ecosystem damages.\n\n## f.\n\n### assumption checking\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(\n  # starting data frame\n  data = kelp,\n  # y-axis: kelp frond elongation rate\n  mapping = aes(sample = kelp_elong)\n) +\n  # first layer: QQ reference line\n  geom_qq_line(\n    # coloring line\n    color = 'navyblue'\n  ) +\n  # second layer: QQ points\n  geom_qq(\n    # coloring points\n    color = 'chartreuse4', \n    # changing opacity\n    alpha = 0.6\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/assumption-checking-2-1.png){width=672}\n:::\n:::\n\n\n### test running\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# correlation test\ncor.test(\n  # y-variable\n  kelp$kelp_elong,\n  # x-variable\n  kelp$temp_c,\n  # use pearsons test\n  method = 'pearson')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  kelp$kelp_elong and kelp$temp_c\nt = -5.189, df = 30, p-value = 1.366e-05\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.8359665 -0.4460157\nsample estimates:\n       cor \n-0.6877489 \n```\n\n\n:::\n:::\n\n\nYes, both tests would have led me to the same decision -- finding a moderate negative relationship and rejecting the null -- as both tests resulted in a moderate negative correlation of -0.69. After running the Pearson's test, I found a moderate negative relationship between ocean temperature and giant kelp frond elongation rate (Pearson's r = -0.69, t(30) = -5.19, p = 1.37 * 10^-5^, $\\alpha$ = 0.05). This conclusion is the same as my conclusion after running the Spearman's test. \n\n# Problem 2\n\n## a.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(\n  # use data frame 'mz_clean'\n  data = mz_clean,\n  # x from 'working_with_others_y_n' col\n  mapping = aes(x = working_with_others_y_n,\n                # y from 'completed_v_intended' col\n                y = completed_v_intended,\n                # coloring by 'working_with_others_y_n'\n                color = working_with_others_y_n,\n                # fill by 'working_with_others_y_n'\n                fill = working_with_others_y_n)\n) +\n  # first layer: boxplot\n  geom_boxplot(\n    # reduce opacity\n    alpha = 0.75\n  ) +\n  # second layer: jitterplot\n  geom_jitter(\n    # remove vertical jitter\n    height = 0,\n    # add horizontal jitter\n    width = 0.2\n  ) +\n  # changing colors\n  scale_color_manual(\n    # 'forestgreen' for 'y'\n    values = c('y' = 'forestgreen',\n               # 'mediumvioletred' for 'n'\n               'n' = 'mediumvioletred')\n  ) +\n  # changing fill colors\n  scale_fill_manual(\n    # 'lawngreen' for 'y'\n    values = c('y' ='lawngreen',\n               # 'violetred' for n\n               'n' = 'violetred1')\n  ) +\n  # changing titles and axes names\n  labs(\n    # label x axis\n    x = 'Working with others (no/yes)',\n    # label y axis\n    y = '% of completed tasks',\n    # change title\n    title = 'Task completion seperated by work type',\n    # change subtitle\n    subtitle = '5/27/26') + \n  # remove legend\n  theme(\n    legend.position = 'none'\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-1-working-with-others-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(\n  # use data frame 'mz_clean'\n  data = mz_clean,\n  # x from 'mood_exhaustion_1_5' col\n  mapping = aes(x = mood_exhaustion_1_5,\n                # y from 'completed_v_intended' col\n                y = completed_v_intended,\n                # group by 'mood_exhaustion_1_5'\n                group = mood_exhaustion_1_5,\n                # fill by 'mood_exhaustion_1_5'\n                fill = mood_exhaustion_1_5,\n                color = mood_exhaustion_1_5)\n) +\n  # first layer: boxplot\n  geom_boxplot(\n    # reduce opacity\n    alpha = 0.75\n  ) +\n  # second layer: jitterplot\n  geom_jitter(\n    # remove vertical jitter\n    height = 0,\n    # add horizontal jitter\n    width = 0.2\n  ) +\n  # changing colors\n  scale_color_manual(\n    # 'darkred' for 'one'\n    values = c('a1' ='darkred',\n               # 'sienna4' for 'two'\n               'b2' = 'sienna4',\n               # 'darkgoldenrod4' for 'three'\n               'c3' = 'darkgoldenrod4',\n               # 'darkgreen' for 'four'\n               'd4' = 'darkgreen',\n               # 'navy' for 'five'\n               'e5' = 'navy')\n  ) +\n  # changing fill colors\n  scale_fill_manual(\n    # 'red' for 'one'\n    values = c('a1' ='red',\n               # 'orange' for 'two'\n               'b2' = 'orange',\n               # 'yellow' for 'three'\n               'c3' = 'yellow',\n               # 'green' for 'four'\n               'd4' = 'green')\n  ) +\n  # changing x-axis displays\n  scale_x_discrete(\n    # a1 to 1\n    labels = c('a1' = '1',\n               # b2 to 2\n               'b2' = '2',\n               # c3 to 3\n               'c3' = '3',\n               # d4 to 4\n               'd4' = '4',\n               # e5 to 5\n               'e5' = '5')\n  ) +\n  # changing titles and axes names\n  labs(\n    # label x axis\n    x = 'Mood (1-4)',\n    # label y axis\n    y = '% of completed tasks',\n    # change title\n    title = 'Task completion seperated by mood',\n    # change subtitle\n    subtitle = '5/27/26') + \n  # remove legend\n  theme(\n    legend.position = 'none'\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-2-mood-1.png){width=672}\n:::\n:::\n\n\n## b.\n\n*Work type figure Caption*: Task Completion Separated by Work Type. Box plots of work completion depending on environment. Pink plot represents working alone, green plot represents working with other. Each data point represents an individual measurement of completed task percentage for the day, from 4/23/26 to 5/27/26. Fences are the IQRs (25th and 75th percentiles), with the median (50th percentile) of collected data per environment as a line in between each respective box. Whiskers represent minimum and maximum values (1.5 x lower or upper IQR bound)   \n\n*Mood figure Caption*: Task Completion Separated by mood. Box plots of work completion depending on a mood scale of 1-4, with 1 being the lowest and 4 being the highest (within the data). Red plot is a mood of 1, orange plot is a mood of 2, yellow plot is a mood of 3, and green plot is a mood of 4. Each data point represents an individual measurement of completed task percentage for the day, from 4/23/26 to 5/27/26. Fences are the IQRs (25th and 75th percentiles), with the median (50th percentile) of collected data per environment as a line in between each respective box. Whiskers represent minimum and maximum values (1.5 x lower or upper IQR bound)   \n\n# Problem 3\n\n## a.\n\nAn affective visualization for my personal data could take the form of a drawing, showing box plots -- representing mood -- that are being climbed/conquered by a person. For example, if a good mood leads to more work being completed, an affective visualization could show a raised large stack of papers (higher box plot) with sticky tabs sticking out (overlaid data) and a confident/smiling person lifting them above their head. Another affective visualization could be another drawing, showing a linear model -- representing work completed -- that is being \"weighed down\" by the amount of things that I have in my bag (representing the time I spend on campus). Both of these \"statistical visualizations\" (boxplot, linear model) would be represented via something like stacks of paper, rather than points/lines indicating work being completed. Ideally these visualizations would make the viewer understand what factors/feelings/emotions are influencing work completion, and better relate/understand the graph.\n\n## b. \n![affective-visualization-sketch](affect-vis-sketch.jpg)\n\n## c.\n![affective-visualization-draft](affect-vis-draft.jpg)\n\n## d. \n\nI am showing an affective representation of how productivity changes depending on activities -- in this case, I am showing productivity as stacks of papers/books being completed, and activities as a bunch of items/things (for instance, a backpack for class, climbing shoes, etc.) that increase as activities increase. I got influences from Jill Pelto's paintings; I really liked how oftentimes data was represented as mountains/rivers/cracks on a glacier, etc. I tried to emulate something similar, showing data as a \"mountain\" of papers. Outside of Jill Pelto, I got influences from my daily life; the items depicted are all reflective of things that I have had to carry around for activities before. The form of my work is going to be a digital drawing -- however, I currently have no access to my drawing software so I am drawing it on paper before transferring it onto my computer. To create my work, I looked at many of the items that I own, and wondered how each one could potentially tie in my actives that I do every day. People have often told me that I always carry way too many things, which made me think about why, and the relationship between my carried items, busyness, and subsequent productivity. I also added some details that I just thought would be fun, and a better representation of me -- for instance, I plan to put a drawing of an album cover that I like in the background, I have a drawing of me doing work on top of the \"mountain\", etc. \n\n## e.\n\n[ENVS 193DS Affective Visualization Presentation](https://docs.google.com/presentation/d/1uCG-GdxWvUQCitZFn2xcTzJ8NKknzWKenxtSjhKxEmk/edit?usp=sharing)\n\n# Problem 4\n\n## a. \n\nIn this paper, the researchers use multiple statistical tests to analyze the effect of landscape differences (size, disturbance, etc.) on shrew population abundance. The statistical tests that the authors are using to address their main research question are linear regression, logsitic regression, ANOVA, Shapiro-Wilk, and the Kruskal-Wallis tests. Attached below is a table created using data from a linear regression test, showing how different landscapes can impact a specifc shrews species (Notiosorex crawfordi) population distribution and abundance.\n\n![linear-regression-graph](lin-reg.png)\n\n## b.\n\nThe table clearly represents the data underlying the tests. It displays each predictor (ex. control, density of scrubs, etc.) and the variables for each predictor used to calculate expected shrew abundance in locales displaying variations of these predictors. This clearly shows the data that the scientists used to run the tests. However, it is lacking in data showing how these variables were found, which is likely in another table.\n\n## c.\n\nThe authors moderately handle visual clutter. While it is clear what is being displayed in the table as there is little non-data information provided, the table itself has inconsistent formatting, with misaligned numbers/columns. However, the \"data:ink ratio\" is very low/good -- the majority of \"ink\" is being used to represent actual data -- there is very little visual clutter relative to the information being presented. Subsequently, while the aesthetics/organization could be better, the visual clutter is low, and the data is clearly communicable.\n\n## d.\n\nTo make this table better, I would relabel the 'Source' column to 'Predictors', reformat/align the data within the columns, and add column lines to help organize my data/make my table look neater. The first change is because the variables listed under 'Source' are all variables that are being used to predict shrew abundance; subsequently, changing the column title will make it clearer to the reader what they are looking at -- they will not have to figure out what 'Source' indicates, and will have a better understanding that these variables are being used as predictors in the linear regression data. The remaining two changes are to improve table organization: currently the data is misaligned with inconsistent margins -- by aligning margins, and putting clear column lines in which to align margins to, the chart will look better and be easier to read.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}